#!/bin/bash
# Rofi prompt to select a search engine, then input a query to search
declare -A URLS
URLS=(
  ["askubuntu"]="http://askubuntu.com/search?q="
  ["bing"]="https://www.bing.com/search?q="
  ["dict"]="https://www.dict.cc/?s="
  ["duckduckgo"]="https://www.duckduckgo.com/?q="
  ["github"]="https://github.com/search?q="
  ["wikipedia.de"]="https://de.wikipedia.org/wiki/"
  ["goodreads"]="https://www.goodreads.com/search?q="
  ["google"]="https://www.google.com/search?q="
  ["imdb"]="http://www.imdb.com/find?ref_=nv_sr_fn&q="
  ["manpages"]="https://man.cx/"
  ["openhub"]="https://www.openhub.net/p?ref=homepage&query="
  ["piratebay"]="https://thepiratebay.org/search/"
  ["reddit"]="https://reddit.com/search?q="
  ["rottentomatoes"]="https://www.rottentomatoes.com/search/?search="
  ["searchcode"]="https://searchcode.com/?q="
  ["stackoverflow"]="http://stackoverflow.com/search?q="
  ["superuser"]="http://superuser.com/search?q="
  ["symbolhound"]="http://symbolhound.com/?q="
  ["vimawesome"]="http://vimawesome.com/?q="
  ["wiktionary"]="https://en.wiktionary.org/wiki/"
  ["yahoo"]="https://search.yahoo.com/search?p="
  ["yandex"]="https://yandex.ru/yandsearch?text="
  ["youtube"]="https://www.youtube.com/results?search_query="
)

# List for rofi
gen_list() {
	for i in "${!URLS[@]}"
	do
		echo "$i"
	done
}

# Pass the list to rofi
# platform="$( (gen_list) | rofi -dmenu -i -p "Search")"
platform="$( (gen_list) | rofi -dmenu -i -p "Search" -show run -lines 8 -eh 1 -padding 40 -columns 3 -font "System San Francisco Display 8")"

[ -z "$platform" ] && exit 1

query="$(rofi -dmenu -i -lines 0 -p "Query")"

if [[ -n "$query" ]]; then
	url="${URLS[$platform]}$query"
	xdg-open "$url"
else
	exit 1
fi
