#!/bin/bash
# Rofi prompt to select a search engine, then input a query to search
declare -A URLS
URLS=(
  ["Ask Ubuntu"]="http://askubuntu.com/search?q="
  ["Bing"]="https://www.bing.com/search?q="
  ["Dict"]="https://www.dict.cc/?s="
  ["DuckDuckGo"]="https://www.duckduckgo.com/?q="
  ["GitHub"]="https://github.com/search?q="
  ["Wikipedia (DE)"]="https://de.wikipedia.org/wiki/"
  ["Goodreads"]="https://www.goodreads.com/search?q="
  ["Google"]="https://www.google.com/search?q="
  ["IMDB"]="http://www.imdb.com/find?ref_=nv_sr_fn&q="
  ["Manpages"]="https://man.cx/"
  ["Openhub"]="https://www.openhub.net/p?ref=homepage&query="
  ["Piratebay"]="https://thepiratebay.org/search/"
  ["reddit"]="https://reddit.com/search?q="
  ["Rottentomatoes"]="https://www.rottentomatoes.com/search/?search="
  ["Searchcode"]="https://searchcode.com/?q="
  ["SearX"]="https://searx.me/?q="
  ["Softwareengineering"]="https://softwareengineering.stackexchange.com/search?q="
  ["Stackoverflow"]="http://stackoverflow.com/search?q="
  ["Stackexchange"]="https://stackexchange.com/search?q="
  ["Superuser"]="http://superuser.com/search?q="
  ["Symbolhound"]="http://symbolhound.com/?q="
  ["Tex"]="https://tex.stackexchange.com/search?q="
  ["RFC"]="http://www.rfc-editor.org/info/rfc"
  ["tl;dr"]="https://tldr.ostera.io/"
  ["Vimawesome"]="http://vimawesome.com/?q="
  ["Wiktionary"]="https://en.wiktionary.org/wiki/"
  ["Yahoo"]="https://search.yahoo.com/search?p="
  ["Yandex"]="https://yandex.ru/yandsearch?text="
  ["YouTube"]="https://www.youtube.com/results?search_query="
)

# List for rofi
gen_list() {
	for i in "${!URLS[@]}"
	do
		echo "$i"
	done
}

# Pass the list to rofi
# platform="$( (gen_list) | rofi -dmenu -i -p "Search")"
platform="$( (gen_list) | rofi -dmenu -i -p "Search" -show run -lines 8 -eh 1 -padding 40 -columns 3 -font "System San Francisco Display 8")"

[ -z "$platform" ] && exit 1

query="$(rofi -dmenu -i -lines 0 -p "Query")"

if [[ -n "$query" ]]; then
	url="${URLS[$platform]}$query"
	xdg-open "$url"
else
	exit 1
fi
